### ISSUE TITLE
Fix Pull Request

### ISSUE THREAD

**Issue by sysarcher** [shrmrf/acrn-hypervisor#5]
The pull request https://github.com/projectacrn/acrn-hypervisor/pull/52 has too many changes. Ideally, my changes should be one or two commits.

Some logs:-

```bash
$ git clone git@github.com:shrmrf/acrn-hypervisor.git
Cloning into 'acrn-hypervisor'...
remote: Counting objects: 1062, done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 1062 (delta 106), reused 221 (delta 85), pack-reused 799
Receiving objects: 100% (1062/1062), 621.79 KiB | 252.00 KiB/s, done.
Resolving deltas: 100% (561/561), done.
Checking connectivity... done.

$ git fetch git@github.com:projectacrn/acrn-hypervisor.git
From github.com:projectacrn/acrn-hypervisor
 * branch            HEAD       -> FETCH_HEAD

$ dos2unix Dockerfile
dos2unix: converting file Dockerfile to Unix format ...
$ vim .travis.yml
$ git diff origin/master > ../my-travis.patch
$ git reset --hard origin/master
HEAD is now at 9600271 Merge branch 'master' into master
$ git apply ../my-travis.patch
../my-travis.patch:10: trailing whitespace.

warning: 1 line adds whitespace errors.
$ git commit -a -s
[master 8c2cf0e] Add .travis.yml and Dockerfile
 2 files changed, 13 insertions(+), 13 deletions(-)
$ git push -f


$ git remote -v
origin  git@github.com:shrmrf/acrn-hypervisor.git (fetch)
origin  git@github.com:shrmrf/acrn-hypervisor.git (push)
```

**Comment by gvancuts** [comment]
I think the issue is that you cloned your own repo first (and it became `origin` by default). I'm not able to force-push to your repo (although you've added me as a collaborator) but the following should help:
```
git remote add upstream git@github.com:projectacrn/acrn-hypervisor.git
git fetch upstream
git checkout origin/master
# Delete the trailing whitespace in .travis.yml
git diff upstream/master > ../my-travis.patch
git reset --hard upstream/master
git apply ../my-travis.patch
git add .travis.yml Dockerfile
git commit -a -s
git push -f origin
```

**Comment by gvancuts** [comment]
Ah, I needed to first accept your invitation to become a collaborator. Now that I've done it, I was able to force-push a new codebase on your master branch. Take a look at the updated PR at https://github.com/projectacrn/acrn-hypervisor/pull/52 (there is a single new commit now).

You should still add your own "Signed-off-by:" line in the commit or if you tell me what email address to use, I can add it for you

**Comment by sysarcher** [comment]
Hey @gvancuts 

Thanks a lot!! 

I think my fault was working at 12 at night :)

Thanks, again!! 

BTW, I amended the last commit message to add my sign-off... (I actually find this a very clunky way but it is how it is..)
