### ISSUE TITLE
Fix Build Environment 

### ISSUE THREAD

**Issue by sysarcher** [shrmrf/acrn-hypervisor#6]
In the current CI setup that we proposed (myself and @gvancuts ), we are depending on a [generic bundle](https://github.com/shrmrf/acrn-hypervisor/blob/master/Dockerfile#L7) which _we_ do not have control over. Will it not be better to set up an environment that has a _fixed_ version of `gcc` etc.? The main advantages would be:-

- Independence from any single Linux distro
- Similar environment for all developers and testers
- Failure conditions can be more easily tested and fixed

Also, then, we can use docker as the only dependency on a Linux machine.

For non-Intel devs (and even Intel devs), it might be simpler to use a glorified `docker build` (or similar) instead of the usual environment setup following wiki pages etc.

**Comment by gvancuts** [comment]
I'm not sure many will see your suggestions here @shrmrf , I would suggest you take this to the acrn-dev mailing list directly.

My take on this is that I would like to see the hypervisor and devicemodel code be somewhat independant of any Linux distro **and** any specific compiler version. We need this to be portable so people can build it for different Service OS and platforms. The other aspect is that ideally you'd build it with the exact same version of the libraries it depends on (this is really for the devicemodel only), and it's easier to make sure we can work with the libraries provided by default by the Linux distribution of choice (for now Clearlinux).

with that in mind, my preference is that we select a few Linux distributions that we validate this on (e.g. latest LTS Ubuntu, Fedora and Clearlinux). If someone wants to compile this on a different dev OS, then they can re-use the containers we have enabled for the CI system.

Does that make sense to you?

**Comment by sysarcher** [comment]
Hey @gvancuts 

Yup. I see your arguments. It's only just a matter of preferences in the end I guess. Fixing the build environment (like `gcc` versions etc.) will just help a user debug the issue with his builds because that'd guarantee running on any distro.

I wanted someone to review the idea before I proposed it to a wider audience. Thanks for your input as always!!
